name: ind_utils
description: ind_utils package use this package for SizedBox and also Padding. No Need to write long code for these`
version: 0.0.8
homepage: https://github.com/ansaralisahh/ind_utils.git
license: MIT


environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: